# Generated by Django 3.2.6 on 2021-08-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('image', models.ImageField(upload_to='album/')),
                ('description', models.TextField()),
                ('time_since', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
